# Generated by Django 5.0.6 on 2024-05-27 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('currency_app', '0003_exchangerate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exchangerate',
            name='country',
            field=models.TextField(max_length=255),
        ),
    ]
